name: squad2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ujson
  - numpy
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pandas
  - matplotlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
    - transformers